# Generated by Django 4.0.4 on 2022-05-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_contact_roll_alter_contact_name_alter_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='roll',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
